# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af8ecc8acf95c1c5327ce929082e4653d78dfa29c85f757f137ad7bcfaaec90e9b7d6d3b133db2a6f9d6fe336357abacc95c9a83b2f7aa98395e5d03aa7d55ce

test:
  secret_key_base: 0520d89ce4990c51effd0ae112ed6b611c3b556ee49415ff9e57715ad05997649f8c2c918408b965f01cc82545d5ef2282b45d870104ea64ca64ac4393e77300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
